modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPL-3.0"
issueTrackerURL="https://github.com/yourusername/gtceu-terminal-addon/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${mod_description}'''
# logoFile="logo.png"

[[dependencies.gtceuterminal]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.gtceuterminal]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.gtceuterminal]]
    modId="gtceu"
    mandatory=true
    versionRange="[7.0.0,)"
    ordering="AFTER"
    side="BOTH"
